# -*- coding: utf-8 -*-
"""MetodeHeun_Jawaban

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u6AYNpF9udRHfa3ae8ZzC1SL3YN5aRqw
"""

#definisikan fungsi f(x)
def f(x,y):
  return (-2)*x*y**2

#heun method
def heun(x0,y0,xn,n):

  #menghitung ukuran langkah xi
  h = (xn-x0)/n

  print('-----------------------------------')
  print('x0\ty0\tfxy\tyn')
  print('-----------------------------------')
  for i in range(n):
    k1 = h * f(x0, y0)
    k2 =  h * (f((x0+h),(y0+k1)))
    k = (k1 + k2)/2
    yn = y0 + k
    print('%.4f\t%.4f\t%.4f' % (x0,y0,yn) )
    print('-----------------------------------')
    y0 = yn
    x0 = x0+h

  print ('\n Jadi x=%.4f, y=%.4f' %(xn,yn) )

#input
print('\n Masukan kondisi awal :')
x0 = float(input('x0 = '))
y0 = float(input('y0 = '))

print('\n Masukan titik yang akan dihitung :')
xn = float(input('xn = '))

print('\n Masukan jumlah iterasi :')
step = int(input('jumlah iterasi = '))

#heun method call
heun (x0,y0,xn,step)