# -*- coding: utf-8 -*-
"""metode bagi dua.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OYhFlTRg7HV_2f4KJ7X02ram0Q8DClXL
"""

from math import e #untuk memanggil bilangan eksponen natural (e)
import numpy as np
import matplotlib.pyplot as plt

#mendefinisikan fungsi
def f(x):
    return e**x-5*x**2

#sesi input nilai awal yang di konversi ke pecahan
x0 = float(input('x0 : '))
x1 = float(input('x1 : '))
eps = float(input('epsilon : '))

#metode bagi dua
def bisection(x0,x1,eps):
    step = 1
    print('\n\n*** ---Metode Bagi Dua--- ***')
    condition = True
    while condition:
        x2 = (x0 + x1)/2
        print('Iterasi-%d, x2 = %0.6f dan f(x2) = %0.6f' % (step, x2, f(x2)))
        if f(x0) * f(x2) < 0:
            x1 = x2
        else:
            x0 = x2
        step = step + 1
        condition = abs(f(x2)) > eps

    print('\n Akar Persamaan tersebut : %0.8f' % x2)

#menggambar fungsi 
rr= np.linspace(0, 2, 100) #masukan nilai tebakan awal
plt.plot(rr, f(rr))
plt.show()
plt.savefig("fungsi.png") #untk menyimpan gambar fungsi

#pengecekan nilai awal
if f(x0) * f(x1) > 0.0:
    print('Nilai yang diprediksi tidak mengurung akar')
    print('silahkan meencoba ulang prediksi nilai baru')
else:
    bisection(x0,x1,eps)