# -*- coding: utf-8 -*-
"""MetodeRungge_kutta_orde4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u6AYNpF9udRHfa3ae8ZzC1SL3YN5aRqw
"""

#metode Runge-kutta orde 4

#definisikan fungsi f(x)
def f(x,y):
  return x+y

#RK orde 4
def RK4(x0,y0,xn,n):

  #menghitung ukuran langkah xi
  h = (xn-x0)/n

  print('-----------------------------------')
  print('x0\ty0\tfxy\tyn')
  print('-----------------------------------')
  for i in range(n):
    k1 = h * f(x0, y0)
    k2 = h * (f((x0+h/2),(y0+k1/2)))
    k3 = h * (f((x0+h/2),(y0+k2/2)))
    k4 = h * (f((x0+h),(y0+k3)))
    k = (k1*2*k2*2*k3+k4)/6
    yn = y0 + k
    print('%.4f\t%.4f\t%.4f' % (x0,y0,yn) )
    print('-----------------------------------')
    y0 = yn
    x0 = x0+h

  print ('\n Jadi x=%.4f, y=%.4f' %(xn,yn) )

#input
print('\n Masukan kondisi awal :')
x0 = float(input('x0 = '))
y0 = float(input('y0 = '))

print('\n Masukan titik yang akan dihitung :')
xn = float(input('xn = '))

print('\n Masukan jumlah iterasi :')
step = int(input('jumlah iterasi = '))

#memanggil metode rk4
RK4(x0,y0,xn,step)