# -*- coding: utf-8 -*-
"""MetodeLangrange

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u6AYNpF9udRHfa3ae8ZzC1SL3YN5aRqw
"""

# interpolasi lagrange

import numpy as np

#Membaca jumlah titik data
n = int(input('masukkan jumlah titik data: '))

#membuat array ukuran n x n dan inisialisasi
x = np.zeros((n))
y = np.zeros((n))


#membuat titik data 
print('masukkan data x dan y: ')
for i in range(n):
  x[i] = float(input( 'x['+str(i)+']='))
  y[i] = float(input( 'y['+str(i)+']='))


#membaca interpolasi titik
xp = float(input('Masukan x yang diinginkan: '))

#implementasi interpolasi lagrange
yp = 0

#implementasi interpolasi lagrange
for i in range(n):

  p = 1

  for j in range(n):
    if i != j:
      p = p * (xp - x[j])/(x[i] - x[j])

    yp = yp + p * y[i]

#displaying output
print('nilai interpolasi untuk %.3f adalah %.3f.' % (xp, yp))