# -*- coding: utf-8 -*-
"""Metodeeuler

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u6AYNpF9udRHfa3ae8ZzC1SL3YN5aRqw
"""

#metode euler

#definisikan fungsi f(x)
def f(x,y):
  return x+y

#euler method
def euler(x0,y0,xn,n):

  #menghitung ukuran langkah xi
  h = (xn-x0)/n

  print('-----------------------------------')
  print('x0\ty0\tfxy\tyn')
  print('-----------------------------------')
  for i in range(n):
    fxy = f(x0, y0)
    yn = y0 + h * fxy
    print('%.4f\t%.4f\t%0.4f\t%.4f' % (x0,y0,fxy,yn) )
    print('-----------------------------------')
    y0 = yn
    x0 = x0+h

  print ('\n Jadi x=%.4f, y=%.4f' %(xn,yn) )

#input
print('\n Masukan kondisi awal :')
x0 = float(input('x0 = '))
y0 = float(input('y0 = '))

print('\n Masukan titik yang akan dihitung :')
xn = float(input('xn = '))

print('\n Masukan jumlah iterasi :')
step = int(input('jumlah iterasi = '))

#euler method call
euler (x0,y0,xn,step)