# -*- coding: utf-8 -*-
"""MetodeRegresi

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u6AYNpF9udRHfa3ae8ZzC1SL3YN5aRqw
"""

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.linear_model import LinearRegression
df = pd.DataFrame([[1,1],[2,1.2],[3,1.8],[4,2.5],[5,3.6],[6,4.7],[7,6.6],[8,9.1]])

df.columns = ['x', 'y']
x_train = df['x'].values[:,np.newaxis]
y_train = df['y'].values
lm = LinearRegression()

lm. fit(x_train,y_train) #fase training

print('coefficient :'+ str(lm.coef_))
print('intercept :'+ str(lm.intercept_))
x_test = [[7],[8]] #data yang akan diprediksi
p = lm.predict(x_test) #fase prediksi
print('hasil prediksi:'+str(p)) #hasil prediksi

#prepare polt
pb = lm.predict(x_train)
dfc = pd.DataFrame({'x' : df['x'], 'y':pb})
plt.scatter(df['x'],dfc['y'])
plt.plot(df['x'],dfc['y'],color='red',linewidth=2)
plt.xlabel('dosis dalam mgr')
plt.ylabel('berat dalam gr')
plt.show()